---
openapi: 3.0.3
info:
  title: Staff API
  description: API for providing staff information
  contact:
    name: VolkerWessels Telecom
    url: "https://www.vwtelecom.com"
    email: support@vwt.digital
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: 1.0.0
  x-audience: company-internal
  x-api-id: 055ed066-4ba6-443c-a9c9-4d5aa0013a36
servers:
  - url: /
paths:
  /departments:
    get:
      summary: Get departments
      description: Get list of departments
      operationId: departments_get
      parameters:
        - $ref: "#/components/parameters/PageCursor"
        - $ref: "#/components/parameters/PageSelector"
        - $ref: "#/components/parameters/PageSize"
      responses:
        200:
          description: Succesful response
          content:
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Department"
          links:
            GetManagerByEmployeeNumber:
              $ref: "#/components/links/GetManagerByEmployeeNumber"
            GetDepartmentEmployeesByDepartmentNumber:
              $ref: "#/components/links/GetDepartmentEmployeesByDepartmentNumber"
            GetDepartmentByDepartmentNumber:
              $ref: "#/components/links/GetDepartmentByDepartmentNumber"
        201:
          description: No Content
        400:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Bad Request
        401:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: No authorization token provided
        403:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Provided token doesn't have the required scope
        404:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Not Found
      security:
        - oauth2: [staff.read]
      x-codegen-request-body-name: body
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /departments/{department_number}:
    get:
      summary: Get department information
      description: Get department information by department number
      operationId: departments_department_get
      parameters:
        - $ref: "#/components/parameters/DepartmentNumber"
      responses:
        200:
          description: Succesful response
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/Department"
          links:
            GetManagerByEmployeeNumber:
              $ref: "#/components/links/GetManagerByEmployeeNumber"
            GetDepartmentEmployeesByDepartmentNumber:
              $ref: "#/components/links/GetDepartmentEmployeesByDepartmentNumber"
            GetDepartmentByDepartmentNumber:
              $ref: "#/components/links/GetDepartmentByDepartmentNumber"
        201:
          description: No Content
        400:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Bad Request
        401:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: No authorization token provided
        403:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Provided token doesn't have the required scope
        404:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Not Found
      security:
        - oauth2: [staff.read]
      x-codegen-request-body-name: body
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /departments/{department_number}/employees:
    get:
      summary: Get department employees
      description: Get list of department employees by department number
      operationId: departments_department_employees_get
      parameters:
        - $ref: "#/components/parameters/DepartmentNumber"
        - $ref: "#/components/parameters/FilterEmployeeName"
      responses:
        200:
          description: Succesful response
          content:
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Employee"
          links:
            GetEmployeeDepartmentByDepartmentNumber:
              $ref: "#/components/links/GetEmployeeDepartmentByDepartmentNumber"
            GetEmployeeManagerByEmployeeNumber:
              $ref: "#/components/links/GetEmployeeManagerByEmployeeNumber"
            GetEmployeeReportsByEmployeeNumber:
              $ref: "#/components/links/GetEmployeeReportsByEmployeeNumber"
        201:
          description: No Content
        400:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Bad Request
        401:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: No authorization token provided
        403:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Provided token doesn't have the required scope
        404:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Not Found
      security:
        - oauth2: [staff.read]
      x-codegen-request-body-name: body
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /employees:
    get:
      summary: Get employees
      description: Get list of employees
      operationId: employees_get
      parameters:
        - $ref: "#/components/parameters/FilterEmployeeName"
        - $ref: "#/components/parameters/PageCursor"
        - $ref: "#/components/parameters/PageSelector"
        - $ref: "#/components/parameters/PageSize"
      responses:
        200:
          description: Succesful response
          content:
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Employee"
          links:
            GetEmployeeDepartmentByDepartmentNumber:
              $ref: "#/components/links/GetEmployeeDepartmentByDepartmentNumber"
            GetEmployeeManagerByEmployeeNumber:
              $ref: "#/components/links/GetEmployeeManagerByEmployeeNumber"
            GetEmployeeReportsByEmployeeNumber:
              $ref: "#/components/links/GetEmployeeReportsByEmployeeNumber"
        201:
          description: No Content
        400:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Bad Request
        401:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: No authorization token provided
        403:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Provided token doesn't have the required scope
        404:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Not Found
      security:
        - oauth2: [staff.read]
      x-codegen-request-body-name: body
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /employees/me:
    get:
      summary: Get active employee
      description: Get active employee by UPN in authorization token
      operationId: employees_me_get
      responses:
        200:
          description: Succesful response
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/Employee"
          links:
            GetEmployeeDepartmentByDepartmentNumber:
              $ref: "#/components/links/GetEmployeeDepartmentByDepartmentNumber"
            GetEmployeeManagerByEmployeeNumber:
              $ref: "#/components/links/GetEmployeeManagerByEmployeeNumber"
            GetEmployeeReportsByEmployeeNumber:
              $ref: "#/components/links/GetEmployeeReportsByEmployeeNumber"
        201:
          description: No Content
        400:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Bad Request
        401:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: No authorization token provided
        403:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Provided token doesn't have the required scope
        404:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Not Found
      security:
        - oauth2: [staff.read]
      x-codegen-request-body-name: body
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /employees/{employee_number}:
    get:
      summary: Get employee information
      description: Get employee information by employee number
      operationId: employees_employee_get
      parameters:
        - $ref: "#/components/parameters/EmployeeNumber"
      responses:
        200:
          description: Succesful response
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/Employee"
          links:
            GetEmployeeDepartmentByDepartmentNumber:
              $ref: "#/components/links/GetEmployeeDepartmentByDepartmentNumber"
            GetEmployeeManagerByEmployeeNumber:
              $ref: "#/components/links/GetEmployeeManagerByEmployeeNumber"
            GetEmployeeReportsByEmployeeNumber:
              $ref: "#/components/links/GetEmployeeReportsByEmployeeNumber"
        201:
          description: No Content
        400:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Bad Request
        401:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: No authorization token provided
        403:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Provided token doesn't have the required scope
        404:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Not Found
      security:
        - oauth2: [staff.read]
      x-codegen-request-body-name: body
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /employees/{employee_number}/reports:
    get:
      summary: Get employee reports
      description: Get a list of employee reports by employee number
      operationId: employees_employee_reports_get
      parameters:
        - $ref: "#/components/parameters/EmployeeNumber"
        - $ref: "#/components/parameters/PageCursor"
        - $ref: "#/components/parameters/PageSelector"
        - $ref: "#/components/parameters/PageSize"
      responses:
        200:
          description: Succesful response
          content:
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Employee"
          links:
            GetEmployeeDepartmentByDepartmentNumber:
              $ref: "#/components/links/GetEmployeeDepartmentByDepartmentNumber"
            GetEmployeeManagerByEmployeeNumber:
              $ref: "#/components/links/GetEmployeeManagerByEmployeeNumber"
            GetEmployeeReportsByEmployeeNumber:
              $ref: "#/components/links/GetEmployeeReportsByEmployeeNumber"
        201:
          description: No Content
        400:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Bad Request
        401:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: No authorization token provided
        403:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Provided token doesn't have the required scope
        404:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Not Found
      security:
        - oauth2: [staff.read]
      x-codegen-request-body-name: body
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /employees/{employee_number}/functions:
    get:
      summary: Get employee functions
      description: Get a list of employee functions by employee number
      operationId: employees_employee_functions_get
      parameters:
        - $ref: "#/components/parameters/EmployeeNumber"
        - $ref: "#/components/parameters/PageCursor"
        - $ref: "#/components/parameters/PageSelector"
        - $ref: "#/components/parameters/PageSize"
      responses:
        200:
          description: Succesful response
          content:
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EmployeeFunction"
          links:
            GetEmployeeDepartmentByDepartmentNumber:
              $ref: "#/components/links/GetEmployeeDepartmentByDepartmentNumber"
            GetManagerByEmployeeNumber:
              $ref: "#/components/links/GetManagerByEmployeeNumber"
            GetFunctionByFunctionID:
              $ref: "#/components/links/GetFunctionByFunctionID"
        201:
          description: No Content
        400:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Bad Request
        401:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: No authorization token provided
        403:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Provided token doesn't have the required scope
        404:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Not Found
      security:
        - oauth2: [staff.read]
      x-codegen-request-body-name: body
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /functions:
    get:
      summary: Get functions
      description: Get list of functions
      operationId: functions_get
      parameters:
        - $ref: "#/components/parameters/PageCursor"
        - $ref: "#/components/parameters/PageSelector"
        - $ref: "#/components/parameters/PageSize"
      responses:
        200:
          description: Succesful response
          content:
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Function"
          links:
            GetManagerByEmployeeNumber:
              $ref: "#/components/links/GetManagerByEmployeeNumber"
            GetDepartmentEmployeesByDepartmentNumber:
              $ref: "#/components/links/GetDepartmentEmployeesByDepartmentNumber"
        201:
          description: No Content
        400:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Bad Request
        401:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: No authorization token provided
        403:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Provided token doesn't have the required scope
        404:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Not Found
      security:
        - oauth2: [staff.read]
      x-codegen-request-body-name: body
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /functions/{function_id}:
    get:
      summary: Get function information
      description: Get function information by ID
      operationId: functions_function_get
      parameters:
        - $ref: "#/components/parameters/FunctionID"
      responses:
        200:
          description: Succesful response
          content:
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Function"
        201:
          description: No Content
        400:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Bad Request
        401:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: No authorization token provided
        403:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Provided token doesn't have the required scope
        404:
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Not Found
      security:
        - oauth2: [staff.read]
      x-codegen-request-body-name: body
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  links:
    GetDepartmentByDepartmentNumber:
      operationId: departments_department_get
      parameters:
        department_number: '$response.body#/id'
      description: >
        The `id` value returned in the response can be used as
        the `department_number` parameter in `GET /departments/{department_number}`.
    GetDepartmentEmployeesByDepartmentNumber:
      operationId: departments_department_employees_get
      parameters:
        department_number: '$response.body#/id'
      description: >
        The `department_number` value returned in the response can be used as
        the `department_number` parameter in `GET /departments/{department_number}/employees`.
    GetManagerByEmployeeNumber:
      operationId: employees_get
      parameters:
        manager_number: '$response.body#/manager_number'
      description: >
        The `manager_number` value returned in the response can be used as
        the `employee_number` parameter in `GET /employees/{employee_number}`.
    GetEmployeeDepartmentByDepartmentNumber:
      operationId: departments_department_get
      parameters:
        department_number: '$response.body#/department/id'
      description: >
        The `department/id` value returned in the response can be used as
        the `department_number` parameter in `GET /departments/{department_number}`.
    GetEmployeeManagerByEmployeeNumber:
      operationId: employees_employee_get
      parameters:
        manager_number: '$response.body#/department/manager_number'
      description: >
        The `department/manager_number` value returned in the response can be used as
        the `employee_number` parameter in `GET /employees/{employee_number}`.
    GetEmployeeReportsByEmployeeNumber:
      operationId: employees_employee_reports_get
      parameters:
        manager_number: '$response.body#/manager_number'
      description: >
        The `manager_number` value returned in the response can be used as
        the `employee_number` parameter in `GET /employees/{employee_number}/reports`.
    GetFunctionByFunctionID:
      operationId: functions_function_get
      parameters:
        manager_number: '$response.body#/id'
      description: >
        The `id` value returned in the response can be used as
        the `function_id` parameter in `GET /functions/{function_id}`.
  parameters:
    DepartmentNumber:
      description: The unique number of a department
      name: department_number
      in: path
      required: true
      style: simple
      schema:
        type: integer
        format: int32
    EmployeeNumber:
      description: The unique number of a employee
      name: employee_number
      in: path
      required: true
      style: simple
      schema:
        type: integer
        format: int32
    FilterEmployeeName:
      description: A filter for the employee name
      explode: true
      in: query
      name: employee_name
      required: false
      schema:
        type: string
      style: form
    PageCursor:
      description: The query cursor of the page
      explode: true
      in: query
      name: page_cursor
      required: false
      schema:
        type: string
        format: byte
      style: form
    PageSelector:
      description: Selector to get next or previous page based on the cursor
      explode: true
      in: query
      name: page_selector
      required: false
      schema:
        default: next
        enum:
          - prev
          - next
        type: string
      style: form
    PageSize:
      description: The numbers of items within a page.
      explode: true
      in: query
      name: page_size
      required: false
      schema:
        default: 50
        maximum: 100
        minimum: 1
        type: integer
      style: form
    FunctionID:
      description: The ID of a function
      name: function_id
      in: path
      required: true
      style: simple
      schema:
        type: integer
        format: int32
  schemas:
    Department:
      title: Department
      description: Department information
      required:
        - _links
        - id
        - manager_number
      type: object
      properties:
        _links:
          type: object
          properties:
            _self:
              $ref: '#/components/schemas/HttpLink'
            manager:
              $ref: '#/components/schemas/HttpLink'
            employees:
              $ref: '#/components/schemas/HttpLink'
            parent:
              $ref: '#/components/schemas/HttpLink'
        ended_at:
          type: string
          format: datetime
        id:
          type: integer
          format: int32
        layer:
          type: integer
          format: int32
        manager_number:
          type: integer
          format: int32
        name:
          type: string
        parent_id:
          type: integer
          format: int32
        started_at:
          type: string
          format: datetime
      example:
        _links:
          _self:
            href: "$url/departments/24"
          manager:
            href: "$url/employees/2345"
          employees:
            href: "$url/departments/24/employees"
          parent:
            href: "$url/departments/23"
        ended_at: null
        id: 24
        layer: 1
        manager_number: 2345
        name: Department 24
        parent_id: 23
        started_at: "2021-01-01T00:00:00Z"
    Employee:
      title: Employee
      description: Employee information
      required:
        - _links
        - employee_number
        - upn
      type: object
      properties:
        _links:
          type: object
          properties:
            _self:
              $ref: '#/components/schemas/HttpLink'
            department:
              $ref: '#/components/schemas/HttpLink'
            manager:
              $ref: '#/components/schemas/HttpLink'
            reports:
              $ref: '#/components/schemas/HttpLink'
            functions:
              $ref: '#/components/schemas/HttpLink'
        department:
          $ref: '#/components/schemas/Department'
        employee_number:
          type: integer
          format: int32
        first_name:
          type: string
        last_name:
          type: string
        mail:
          type: string
          format: email
        function:
          $ref: '#/components/schemas/EmployeeFunction'
        upn:
          type: string
          format: email
      example:
        _links:
          _self:
            href: "$url/employees/1234"
          department:
            href: "$url/departments/24"
          manager:
            href: "$url/employees/2345"
          reports:
            href: "$url/employees/1234/reports"
          functions:
            href: "$url/employees/1234/functions"
        department:
          _links:
            _self:
              href: "$url/departments/24"
            manager:
              href: "$url/employees/2345"
            employees:
              href: "$url/departments/24/employees"
            parent:
              href: "$url/departments/23"
          ended_at: null
          id: 24
          layer: 1
          manager_number: 2345
          name: Department 24
          parent_id: 23
          started_at: "2021-01-01T00:00:00Z"
        employee_number: 1234
        first_name: John
        last_name: Doe
        mail: "random@recognize.nl"
        function:
          _links:
            _self:
              href: "$url/employees/1234"
            manager:
              href: "$url/employees/2345"
            function:
              href: "$url/functions/123456789"
          ended_at: null
          id: 123456789
          manager_number: 2345
          name: Function
          started_at: "2021-01-01T00:00:00Z"
          type: 9
        upn: "random@recognize.nl"
    EmployeeFunction:
      title: Employee function
      description: Employee Function
      required:
        - _links
        - id
      type: object
      properties:
        _links:
          type: object
          properties:
            _self:
              $ref: '#/components/schemas/HttpLink'
            manager:
              $ref: '#/components/schemas/HttpLink'
            function:
              $ref: '#/components/schemas/HttpLink'
        ended_at:
          type: string
          format: datetime
        id:
          type: integer
          format: int32
        manager_number:
          type: integer
          format: int32
        name:
          type: string
        started_at:
          type: string
          format: datetime
        type:
          type: integer
          format: int32
      example:
        _links:
          _self:
            href: "$url/employees/1234"
          manager:
            href: "$url/employees/2345"
          function:
            href: "$url/functions/123456789"
        ended_at: null
        id: 123456789
        manager_number: 2345
        name: Function
        started_at: "2021-01-01T00:00:00Z"
        type: 9
    Function:
      title: Function
      description: Function
      required:
        - _links
        - id
      type: object
      properties:
        _links:
          type: object
          properties:
            _self:
              $ref: '#/components/schemas/HttpLink'
        id:
          type: integer
          format: int32
        name:
          type: string
        type:
          type: integer
          format: int32
      example:
        _links:
          _self:
            href: "$url/functions/123456789"
        id: 123456789
        name: Function
        type: 9
    HttpLink:
      description: A base type of objects representing links to resources.
      type: object
      properties:
        href:
          description: Any URI that is using http or https protocol
          type: string
          format: uri
      required:
        - href
  securitySchemes:
    oauth2:
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow.
      flows:
        implicit:
          authorizationUrl: https://azuread.url/2.0/authorize
          scopes:
            staff.read: Read access to Staff API
      x-tokenInfoFunc: openapi_server.controllers.security_controller_.info_from_oAuth2
      x-scopeValidateFunc: connexion.decorators.security.validate_scope
